travis:
  secure:
    BINSTAR_TOKEN: H6S1GPeHumH6ZGHRhqVt2C3k56EWQieZzTZD4CiN2anofvHvxIxFYQpZ/Nl5i2nUjsgoj7EEFYSmEhY70AYUWXv6CKQPM5VedNU4LfVhGo5xV7P4B+jbODYoeLZ0zht0kQpTvrUZVRhIi5LJBx/gQBDYtoUhHUxM8bC3TbhyjeaFk2n9LYgKpi8phSia9yv+eBKGM2+3mEuxdfHaSzhBsJCd+GlgEAhiwE4bMCRUVJRxP+1SM1jNzIpyLsVEwV0Pjsdq1D3bB0xzc8I/sG7bFgI4CGWTacG63+assXcXlJwqruOXf7eWh8Sao93bwv1YroHzIQcJBZq9DYxwSht5hyldBLIB8gJqD59O9zdw4VGg/TW23/tpuYdE8rsEM7tYvJNn9EvnJq70zgB/HHW98wOZe3gdopNeJl5ljwwxyZYKI/yhWusfUKXYil414mZNRQjAen4SvgjKkO+LxI1lWEdT5mYNS84nIltNBu4ZxpQ3PYkNkr+45n7wlRzFWSpNWGFUNhTEkMMnwI7F7dxkqTNLBv3CDyPnHIMitNlTPH5z4lJqSxPeI/CWi5vkYPXBuJ4oQx8jA6PtC67by2LZdwMOsJP7ohsbW5S9NoQEQ5buuJBri7kSG+GaaJGG6jzM1fFGS4YrtTy5vh4vORFYxF9eqMMS59ohMMrPEs8fxxA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
